[package]
name = "aml"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "sgemm"
harness = false

[dependencies]
half = "2.3.1"
rayon = "1.8.1"

[dev-dependencies]
criterion = {version = "0.3", features = ["html_reports"]}
byteorder = "1.5.0"
float-cmp = "0.9.0"
rand = "0.8.5"
