[package]
name = "aml"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "sgemm"
harness = false

[dependencies]
half = "2.3.1"

[dev-dependencies]
criterion = "0.3"
byteorder = "1.5.0"
float-cmp = "0.9.0"
rand = "0.8.5"
